site_name: Ruixiang's Notes
theme:
  name: material
  logo: assets/logo.png
  favicon: assets/favicon.png
  features:
    - optimize
    - navigation.instant
    - navigation.tracking
    - navigation.path
    - navigation.top
    - navigation.indexes
    # - navigation.expand
    - content.code.copy
  palette:
    # Palette toggle for light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: white
      toggle:
        icon: material/brightness-7 
        name: Switch to dark mode

    # Palette toggle for dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
plugins:
    - search
    - awesome-pages
markdown_extensions:
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.inlinehilite
  - pymdownx.snippets
  - pymdownx.superfences
