name: Publish docs via GitHub Pages
on:
  push:
    branches:
      - main

env:
  GITHUB_TOKEN: ${{secrets.GITHUB_TOKEN}}

jobs:
  build:
    name: Deploy docs
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout main
        uses: actions/checkout@v3

      - name: Install dependencies
        run: sudo apt-get update && sudo apt-get install -y python3-pip && \
          pip install mkdocs-material mkdocs-awesome-pages-plugin

      - name: Deploy docs
        run: mkdocs gh-deploy
